#input from SK USER FIRST NAME AND LAST NAME EMAILN ID C
#VALIDATE CHECKS
#THEN ASK USER FOR PINCODE AND MOBILE NUMBER VALIDATE PINCODE AND NUMBER
#ASK USER TO ENTER HIS USENRMAE AND PASSOWORD
#NOW YOU GOING TO PRINT FINAL OUTPUT THAT USER HAS ENTERED 
#IF USENAME AND PASS ARE CORREFT PRINT USER DETAILS LIKE -> 
#USERSFULLNMAE,EMAIL, MOBILENO AND PINCODE
